{
 "title": "Garmin Stats",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "ActivityGPS",
    "label": "Activity with GPS",
    "query": {
     "query": "SHOW TAG VALUES FROM \"ActivityGPS\" WITH KEY = \"ActivitySelector\" WHERE $timeFilter"
    }
   }
  ]
 },
 "panels": [
  { "title": "Intraday Health Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Support Me!",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<center><a href='https://ko-fi.com/A0A84F3DP' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi2.png?v=6' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a></center>  "
   }
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "alias": "Heart Rate",
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Sync ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate Distribution",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Heart rate histogram",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value <= 96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram > 96",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram < 60",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value < 60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram > 110",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 110",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 10 },
   "targets": [
    {
     "alias": "Stress",
     "measurement": "StressIntraday",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Body Battery",
     "measurement": "BodyBatteryIntraday",
     "select": [
      [
       { "params": [ "BodyBatteryLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today RHR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Steps",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalSteps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Intraday Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Intraday Steps",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "StepsIntraday",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "StepsCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today SpO2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "averageSpo2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Breathing Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 26 },
   "targets": [
    {
     "alias": "BR",
     "measurement": "BreathingRateIntraday",
     "select": [
      [
       { "params": [ "BreathingRate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Sleep Hours",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Total Asleep",
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Movement Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 33 },
   "targets": [
    {
     "alias": "Sleeping Movement Activity",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "SleepMovementActivityLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "High Stress Duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Stress",
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Intraday Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 40 },
   "targets": [
    {
     "alias": "Sleeping Heart Rate",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "heartRate" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "SpO2",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "spo2Reading" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "HRV",
     "measurement": "HRV_Intraday",
     "select": [
      [
       { "params": [ "hrvValue" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Sleep",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Deep",
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deepSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Light",
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lightSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "REM",
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "remSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Awake",
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "awakeSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today Activity",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sedentary",
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sedentarySeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Intense Activity",
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highlyActiveSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Fair Activity",
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Sleeping",
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Stages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 48 },
   "targets": [
    {
     "alias": "Sleep Stages",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Recent Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Activity HR Zones (mean)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Zone 1",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Zone 2",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Zone 3",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_3" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Zone 4",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_4" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Zone 5",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_5" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity Calories (mean)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "calories",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "calories" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "BMR calories",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "bmrCalories" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity HR difference (Max-Avg)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "alias": "avgHR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "averageHR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "maxHR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "maxHR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPS Track by Velocity",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "alias": "lat",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "lon",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "HR",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "speed",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track by Heart Rate",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "alias": "lat",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "lon",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "HR",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "speed",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track Heart Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "HR",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track pace",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "alias": "Speed",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track Altitude",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Altitude",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Altitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "Activities",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "alias": "Activity Timeline",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "activityType" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Band wearing ",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "HeartRateIntraday",
     "query": "SELECT mean(value) FROM \"heartrate\" WHERE $timeFilter GROUP BY time(2m) fill(0)",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recent Activity",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Activity Type",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "activityType" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ]
    },
    {
     "alias": "Duration",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "elapsedDuration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ]
    },
    {
     "alias": "Max HR",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "maxHR" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ]
    },
    {
     "alias": "Max Speed",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "maxSpeed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ]
    },
    {
     "alias": "Distance",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ]
    },
    {
     "alias": "Location",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "locationName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ]
    }
   ]
  },
  { "title": "Long term visualization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Daily Steps",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Steps",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalSteps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Distance",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "Distance Covered",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalDistanceMeters" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Calories",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "BMR Calories",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bmrKilocalories" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Activity Calories",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeKilocalories" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily avg health matrices",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Avg SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "averageSpO2Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Avg HRV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HRV_Intraday",
     "select": [
      [
       { "params": [ "hrvValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Avg Resting HR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily avg health matrices ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Avg Breathing Rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BreathingRateIntraday",
     "select": [
      [
       { "params": [ "BreathingRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Avg Stress",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StressIntraday",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Avg Sleeping Stress",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "avgSleepStress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Stages",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Deep Sleep",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "deepSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Light Sleep",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "lightSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "REM Sleep",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "remSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "awakeSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Activity over given duration",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sedentarySeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highlyActiveSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Fair Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sleeping",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Score",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Sleep Score",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "sleepScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Activity Overview",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Sleeping",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sedentarySeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Highly Active",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highlyActiveSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Body Battery overview",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Charged",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryChargedValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Drained",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryDrainedValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Intensity Minutes",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Moderate Intensity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "moderateIntensityMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Vigorous Intensity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "vigorousIntensityMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stress overview",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Low Stress duration",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "lowStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Rest stress duration",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Medium stress duration",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "mediumStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Uncategorized stress duration",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "uncategorizedStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "High stress duration",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Sleep trends",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deepSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lightSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "remSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "awakeSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "alias": "Weight in KG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BodyComposition",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Body Battery Level Change",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 170 },
   "targets": [
    {
     "alias": "bb_low",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryLowestValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "bb_high",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryHighestValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly walk heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Hourly Steps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StepsIntraday",
     "select": [
      [
       { "params": [ "StepsCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Regularity",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 177 },
   "targets": [
    {
     "alias": "Sleep Regularity",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "SleepIntraday",
     "query": "SELECT median(\"level\") FROM \"Sleep Levels\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  }
 ]
}